from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date, timedelta
from pathlib import Path

from .config import BTC_DIR, DRYRUN_DIR, FACT_PACKS_DIR, RAW_DIR, SCENARIOS_DIR
from .facts import build_fact_pack, calls_by_index


def crm_record(brief: dict) -> dict:
    crm=json.loads((BTC_DIR / "catalog/crm_seed.json").read_text(encoding="utf-8"))["customers"]
    return next((c for c in crm if c["customer_id"] == brief.get("customer_id")), {"customer_id": brief.get("customer_id"), "name": "Khách hàng", "honorific": "anh/chị", "phone": "<NEW>"})


def derive_success_if(call: dict, pack: dict) -> dict | None:
    outcome=call["expected_outcome"]; product=(pack.get("products") or [{}])[0]; sku=product.get("sku"); price=product.get("quote", {}).get("final_price_vnd")
    if outcome == "chot_don": return {"tool_called":"order.create", "args_match":{"sku":sku, "price_vnd":price}}
    if outcome == "hen_goi_lai": return {"tool_called":"schedule.callback"}
    if outcome == "chuyen_may": return {"tool_called":"handoff.transfer"}
    return {"tool_called":None, "must_say_any":["không có thông tin", "chưa có thông tin"], "must_not_call_tools":True}


def derive_ground_truth(pack: dict) -> dict:
    product=(pack.get("products") or [{}])[0]; quote=product.get("quote", {}); inventory=product.get("inventory", {})
    result={"price_vnd":quote.get("final_price_vnd"), "list_price_vnd":quote.get("list_price_vnd"), "in_stock":inventory.get("in_stock")}
    if inventory.get("restock_expected") is not None: result["restock_date"]=inventory["restock_expected"]
    if "freeship" in quote: result["freeship"]=quote["freeship"]
    for promo in quote.get("applied_promos", []): result[f"promo_{promo['promo_code']}_active"]=True
    for promo in quote.get("expired_promos", []): result[f"promo_{promo}_active"]=False
    return result


def assemble_scenario(brief: dict, raw_by_call: dict[int, dict], packs_by_call: dict[int, dict]) -> dict:
    """The single brief -> BTC schema mapping function."""
    customer=crm_record(brief); previous_facts={}; calls={}
    for call_index in sorted(c["call_index"] for c in brief["calls"]):
        spec=next(c for c in brief["calls"] if c["call_index"] == call_index); pack=packs_by_call[call_index]; dialogue=raw_by_call[call_index]["dialogue"]
        customer_turns=[x["text"] for x in dialogue if x["role"] == "customer"]
        known=set(previous_facts) | {"customer_id", "customer_name", "honorific"}
        must_not_ask=sorted(known & {"room_area_m2","budget_vnd","product_advised","price_quoted_vnd","blocker","address_confirmed","order_id"})
        carry=sorted(set(previous_facts) & {"product_advised","price_quoted_vnd","room_area_m2","budget_vnd","blocker","competitor_context","old_promotion_mentioned"})
        call_out={"call_date":pack["call_date"], "channel":brief["channel"], "channel_identity":brief["channel"], "customer_goal":spec["customer_goal"], "customer_turns":customer_turns,
                  "facts_established":spec.get("facts_to_establish", {}), "must_carry_over":carry, "must_not_ask":must_not_ask,
                  "success_if":derive_success_if(spec, pack), "ground_truth_facts":derive_ground_truth(pack), "expected_outcome":spec["expected_outcome"]}
        if spec.get("input_mode"): call_out["input_mode"]=spec["input_mode"]
        previous_facts.update(spec.get("facts_to_establish", {})); product=(pack.get("products") or [{}])[0]; previous_facts["product_advised"]=product.get("sku"); previous_facts["price_quoted_vnd"]=product.get("quote",{}).get("final_price_vnd")
        calls[f"call_{call_index}"]=call_out
    return {"scenario_id":brief["brief_id"], "customer_id":brief.get("customer_id"), "level":"M1", "persona":brief["persona_id"], "hard_case":("_".join(brief.get("hard_case_tags", [])) or None), "customer_phone":customer.get("phone"), "customer_name":customer.get("name"), "honorific":customer.get("honorific"), "notes":"Generated by data_gen; customer_id is retained as pipeline metadata for CRM traceability; agent_turns remain review-only in generation_review.", "calls":calls}


def run(brief_path: Path, dry_run: bool) -> Path:
    brief=json.loads(brief_path.read_text(encoding="utf-8")); raw={}; packs={}
    for call in brief["calls"]:
        index=call["call_index"]; pack_path=FACT_PACKS_DIR / f"{brief['brief_id']}_c{index}.json"; raw_path=RAW_DIR / f"{brief['brief_id']}_c{index}.json"
        if not pack_path.exists(): pack_path.write_text(json.dumps(build_fact_pack(brief,index), ensure_ascii=False, indent=2), encoding="utf-8")
        if not raw_path.exists(): raise FileNotFoundError(f"Missing raw dialogue {raw_path}; run gen_dialogue first")
        packs[index]=json.loads(pack_path.read_text(encoding="utf-8")); raw[index]=json.loads(raw_path.read_text(encoding="utf-8"))
    scenario=assemble_scenario(brief, raw, packs); out_dir=DRYRUN_DIR if dry_run else SCENARIOS_DIR; out=out_dir / f"{brief['brief_id']}.json"; out.write_text(json.dumps(scenario, ensure_ascii=False, indent=2), encoding="utf-8"); return out


def main() -> None:
    ap=argparse.ArgumentParser(); ap.add_argument("--brief", required=True); ap.add_argument("--dry-run", action="store_true"); args=ap.parse_args(); print(run(Path(args.brief), args.dry_run))


if __name__ == "__main__": main()
